apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: bytedesk-redis
  name: bytedesk-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: bytedesk-redis
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.36.0 (HEAD)
      labels:
        io.kompose.service: bytedesk-redis
    spec:
      containers:
        - env:
            - name: REDIS_ARGS
              value: --requirepass qfRxz3tVT8Nh
          image: redis/redis-stack-server:latest
          name: redis-bytedesk
          ports:
            - containerPort: 6379
              protocol: TCP
          volumeMounts:
            - mountPath: /data
              name: redis-data
      restartPolicy: Always
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-data
