apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: bytedesk-elasticsearch
  name: bytedesk-elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: bytedesk-elasticsearch
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.36.0 (HEAD)
      labels:
        io.kompose.service: bytedesk-elasticsearch
    spec:
      containers:
        - env:
            - name: ELASTIC_PASSWORD
              value: bytedesk123
            - name: ES_JAVA_OPTS
              value: -Xms512m -Xmx512m
            - name: bootstrap.memory_lock
              value: "true"
            - name: cluster.name
              value: bytedesk-es-cluster
            - name: discovery.type
              value: single-node
            - name: node.name
              value: bytedesk-es01
            - name: xpack.security.enabled
              value: "true"
          image: docker.elastic.co/elasticsearch/elasticsearch:8.18.0
          name: elasticsearch-bytedesk
          ports:
            - containerPort: 9200
              protocol: TCP
            - containerPort: 9300
              protocol: TCP
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: elasticsearch-data
      restartPolicy: Always
      volumes:
        - name: elasticsearch-data
          persistentVolumeClaim:
            claimName: elasticsearch-data
