apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: bytedesk
  name: bytedesk
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: bytedesk
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.36.0 (HEAD)
      labels:
        io.kompose.service: bytedesk
    spec:
      containers:
        - env:
            - name: ALIYUN_SMS_SIGNNAME
            - name: ALIYUN_SMS_TEMPLATECODE
            - name: BYTEDESK_ADMIN_EMAIL
              value: admin@email.com
            - name: BYTEDESK_ADMIN_EMAIL_WHITELIST
              value: 100@email.com,101@email.com,102@email.com,103@email.com,104@email.com,105@email.com
            - name: BYTEDESK_ADMIN_MOBILE
              value: "13345678000"
            - name: BYTEDESK_ADMIN_MOBILE_WHITELIST
              value: 18888888000,18888888001,18888888002,18888888003,18888888004,18888888005
            - name: BYTEDESK_ADMIN_NICKNAME
              value: SuperAdmin
            - name: BYTEDESK_ADMIN_PASSWORD
              value: admin
            - name: BYTEDESK_ADMIN_VALIDATE_CODE
              value: "123456"
            - name: BYTEDESK_CACHE_LEVEL
              value: "0"
            - name: BYTEDESK_CACHE_PREFIX
              value: bytedeskim
            - name: BYTEDESK_CACHE_REDIS_STREAM_KEY
              value: bytedeskim:stream
            - name: BYTEDESK_CLUSTER_ENABLED
              value: "false"
            - name: BYTEDESK_CUSTOM_ALLOW_REGISTER
              value: "true"
            - name: BYTEDESK_CUSTOM_DOC_URL
              value: https://www.weiyuai.cn/docs/zh-CN/
            - name: BYTEDESK_CUSTOM_DOC_URL_SHOW
              value: "true"
            - name: BYTEDESK_CUSTOM_ENABLED
              value: "false"
            - name: BYTEDESK_CUSTOM_FORCE_VALIDATE_EMAIL
              value: "true"
            - name: BYTEDESK_CUSTOM_FORCE_VALIDATE_MOBILE
              value: "true"
            - name: BYTEDESK_CUSTOM_LANG
              value: zh-CN
            - name: BYTEDESK_CUSTOM_LOGIN_MOBILE_ENABLE
              value: "true"
            - name: BYTEDESK_CUSTOM_LOGIN_SCAN_ENABLE
              value: "true"
            - name: BYTEDESK_CUSTOM_LOGIN_USERNAME_ENABLE
              value: "true"
            - name: BYTEDESK_CUSTOM_PRIVACY_POLICY_URL
              value: https://www.weiyuai.cn/privacy.html
            - name: BYTEDESK_CUSTOM_SHOW_DEMO
              value: "false"
            - name: BYTEDESK_CUSTOM_SHOW_RIGHT_CORNER_CHAT
              value: "false"
            - name: BYTEDESK_CUSTOM_TERMS_OF_SERVICE_URL
              value: https://www.weiyuai.cn/terms.html
            - name: BYTEDESK_DEBUG
              value: "false"
            - name: BYTEDESK_FEATURES_AVATAR_BASE_URL
              value: http://127.0.0.1:9003
            - name: BYTEDESK_FEATURES_EMAIL_TYPE
              value: javamail
            - name: BYTEDESK_FEATURES_JAVA_AI
              value: "true"
            - name: BYTEDESK_JWT_EXPIRATION
              value: "2592000000"
            - name: BYTEDESK_JWT_REFRESH_TOKEN_EXPIRATION
              value: "5184000000"
            - name: BYTEDESK_JWT_SECRET_KEY
              value: 1dfaf8d004207b628a9a6b859c429f49a9a7ead9fd8161c1e60847aeef06dbd2
            - name: BYTEDESK_KBASE_API_URL
              value: http://127.0.0.1:9003
            - name: BYTEDESK_KBASE_HTML_PATH
              value: helpcenter
            - name: BYTEDESK_KBASE_THEME
              value: default
            - name: BYTEDESK_MEMBER_PASSWORD
              value: "123456"
            - name: BYTEDESK_MINIO_ACCESS_KEY
              value: minioadmin
            - name: BYTEDESK_MINIO_BUCKET_NAME
              value: bytedesk
            - name: BYTEDESK_MINIO_ENABLED
              value: "false"
            - name: BYTEDESK_MINIO_ENDPOINT
              value: http://bytedesk-minio:9000
            - name: BYTEDESK_MINIO_REGION
              value: us-east-1
            - name: BYTEDESK_MINIO_SECRET_KEY
              value: minioadmin123
            - name: BYTEDESK_MINIO_SECURE
              value: "false"
            - name: BYTEDESK_ORGANIZATION_CODE
              value: bytedesk
            - name: BYTEDESK_ORGANIZATION_NAME
              value: MyCompany
            - name: BYTEDESK_SOCKET_CHILD_EVENT_LOOP_GROUP_THREAD_COUNT
              value: "8"
            - name: BYTEDESK_SOCKET_HOST
              value: 0.0.0.0
            - name: BYTEDESK_SOCKET_LEAK_DETECTOR_LEVEL
              value: SIMPLE
            - name: BYTEDESK_SOCKET_MAX_PAYLOAD_SIZE
              value: "10240"
            - name: BYTEDESK_SOCKET_PARENT_EVENT_LOOP_GROUP_THREAD_COUNT
              value: "1"
            - name: BYTEDESK_SOCKET_WEBSOCKET_PORT
              value: "9885"
            - name: BYTEDESK_TESTING_DISABLE_CAPTCHA
              value: "false"
            - name: BYTEDESK_TESTING_DISABLE_IP_FILTER
              value: "false"
            - name: BYTEDESK_TESTING_ENABLED
              value: "false"
            - name: BYTEDESK_UPLOAD_DIR
              value: /app/uploads
            - name: BYTEDESK_UPLOAD_TYPE
              value: local
            - name: BYTEDESK_UPLOAD_URL
              value: http://127.0.0.1:9003
            - name: BYTEDESK_VERSION
              value: 0.9.0
            - name: LOGGING_LEVEL_COM_BYTEDESK_AI
              value: DEBUG
            - name: LOGGING_LEVEL_COM_BYTEDESK_CORE
              value: DEBUG
            - name: LOGGING_LEVEL_COM_BYTEDESK_KBASE
              value: DEBUG
            - name: LOGGING_LEVEL_COM_BYTEDESK_SERVICE
              value: DEBUG
            - name: LOGGING_LEVEL_COM_BYTEDESK_SHOP
              value: DEBUG
            - name: LOGGING_LEVEL_COM_BYTEDESK_SOCIAL
              value: DEBUG
            - name: LOGGING_LEVEL_COM_BYTEDESK_STARTER
              value: DEBUG
            - name: LOGGING_LEVEL_COM_BYTEDESK_TEAM
              value: DEBUG
            - name: LOGGING_LEVEL_COM_BYTEDESK_TICKET
              value: DEBUG
            - name: LOGGING_LEVEL_COM_BYTEDESK_WECHAT
              value: DEBUG
            - name: MANAGEMENT_ENDPOINTS_ENABLED_BY_DEFAULT
              value: "false"
            - name: MANAGEMENT_ENDPOINTS_WEB_BASE_PATH
              value: /management
            - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_EXCLUDE
              value: '*'
            - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
            - name: MANAGEMENT_ENDPOINT_HEALTH_ENABLED
              value: "false"
            - name: MANAGEMENT_ENDPOINT_INFO_ENABLED
              value: "false"
            - name: MANAGEMENT_SERVER_PORT
              value: "-1"
            - name: MANAGEMENT_TRACING_ENABLED
              value: "false"
            - name: MANAGEMENT_TRACING_SAMPLING_PROBABILITY
              value: "0"
            - name: MANAGEMENT_ZIPKIN_TRACING_ENABLED
              value: "false"
            - name: SERVER_PORT
              value: "9003"
            - name: SPRINGDOC_API_DOCS_ENABLED
              value: "true"
            - name: SPRINGDOC_API_DOCS_PATH
              value: /v3/api-docs
            - name: SPRINGDOC_SHOW_ACTUATOR
              value: "false"
            - name: SPRINGDOC_SWAGGER_UI_ENABLED
              value: "true"
            - name: SPRINGDOC_SWAGGER_UI_PATH
              value: /index.html
            - name: SPRING_AI_BAIDU_API_KEY
              value: bce-v3/xxx
            - name: SPRING_AI_BAIDU_BASE_URL
              value: https://qianfan.baidubce.com/v2
            - name: SPRING_AI_BAIDU_CHAT_ENABLED
              value: "false"
            - name: SPRING_AI_BAIDU_CHAT_OPTIONS_MODEL
              value: ernie-x1-32k-preview
            - name: SPRING_AI_BAIDU_CHAT_OPTIONS_TEMPERATURE
              value: "0.7"
            - name: SPRING_AI_DASHSCOPE_API_KEY
              value: sk-xxx
            - name: SPRING_AI_DASHSCOPE_AUDIO_SYNTHESIS_ENABLED
              value: "false"
            - name: SPRING_AI_DASHSCOPE_AUDIO_TRANSCRIPTION_ENABLED
              value: "false"
            - name: SPRING_AI_DASHSCOPE_BASE_URL
              value: https://dashscope.aliyuncs.com
            - name: SPRING_AI_DASHSCOPE_CHAT_ENABLED
              value: "false"
            - name: SPRING_AI_DASHSCOPE_CHAT_OPTIONS_MODEL
              value: qwen-max
            - name: SPRING_AI_DASHSCOPE_CHAT_OPTIONS_TEMPERATURE
              value: "0.7"
            - name: SPRING_AI_DASHSCOPE_CHAT_OPTIONS_TOP_P
              value: "3"
            - name: SPRING_AI_DASHSCOPE_EMBEDDING_ENABLED
              value: "false"
            - name: SPRING_AI_DASHSCOPE_EMBEDDING_OPTIONS_MODEL
              value: text-embedding-v1
            - name: SPRING_AI_DASHSCOPE_ENABLED
              value: "false"
            - name: SPRING_AI_DASHSCOPE_IMAGE_ENABLED
              value: "false"
            - name: SPRING_AI_DEEPSEEK_API_KEY
              value: sk-xxx
            - name: SPRING_AI_DEEPSEEK_BASE_URL
              value: https://api.deepseek.com
            - name: SPRING_AI_DEEPSEEK_CHAT_ENABLED
              value: "false"
            - name: SPRING_AI_DEEPSEEK_CHAT_OPTIONS_MODEL
              value: deepseek-chat
            - name: SPRING_AI_DEEPSEEK_CHAT_OPTIONS_TEMPERATURE
              value: "0.7"
            - name: SPRING_AI_DEEPSEEK_EMBEDDING_ENABLED
              value: "false"
            - name: SPRING_AI_GITEE_API_KEY
              value: sk-xxx
            - name: SPRING_AI_GITEE_BASE_URL
              value: https://ai.gitee.com
            - name: SPRING_AI_GITEE_CHAT_ENABLED
              value: "false"
            - name: SPRING_AI_GITEE_CHAT_OPTIONS_MODEL
              value: Qwen/QwQ-32B
            - name: SPRING_AI_GITEE_CHAT_OPTIONS_TEMPERATURE
              value: "0.7"
            - name: SPRING_AI_MCP_CLIENT_ENABLED
              value: "false"
            - name: SPRING_AI_MCP_SERVER_ENABLED
              value: "false"
            - name: SPRING_AI_MCP_SERVER_STDIO
              value: "false"
            - name: SPRING_AI_MCP_SERVER_TYPE
              value: SYNC
            - name: SPRING_AI_MODEL_AUDIO
              value: zhipuai
            - name: SPRING_AI_MODEL_CHAT
              value: zhipuai
            - name: SPRING_AI_MODEL_EMBEDDING
              value: zhipuai
            - name: SPRING_AI_MODEL_RERANK
              value: dashscope
            - name: SPRING_AI_MODEL_VISION
              value: zhipuai
            - name: SPRING_AI_OLLAMA_BASE_URL
              value: http://host.docker.internal:11434
            - name: SPRING_AI_OLLAMA_CHAT_ENABLED
              value: "false"
            - name: SPRING_AI_OLLAMA_CHAT_OPTIONS_MODEL
              value: qwen3:0.6b
            - name: SPRING_AI_OLLAMA_CHAT_OPTIONS_TEMPERATURE
              value: "0.7"
            - name: SPRING_AI_OLLAMA_EMBEDDING_ENABLED
              value: "false"
            - name: SPRING_AI_OLLAMA_EMBEDDING_OPTIONS_MODEL
              value: bge-m3:latest
            - name: SPRING_AI_OLLAMA_EMBEDDING_OPTIONS_MODEL_RERANK
              value: bge-reranker-v2-m3:latest
            - name: SPRING_AI_OLLAMA_INIT_PULL_MODEL_STRATEGY
              value: when_missing
            - name: SPRING_AI_OPENAI_API_KEY
              value: sk-xxx
            - name: SPRING_AI_OPENAI_BASE_URL
              value: https://api.openai.com
            - name: SPRING_AI_OPENAI_CHAT_ENABLED
              value: "false"
            - name: SPRING_AI_OPENAI_CHAT_OPTIONS_MODEL
              value: gpt-4o
            - name: SPRING_AI_OPENAI_CHAT_OPTIONS_TEMPERATURE
              value: "0.7"
            - name: SPRING_AI_OPENAI_EMBEDDING_ENABLED
              value: "false"
            - name: SPRING_AI_SILICONFLOW_API_KEY
              value: sk-xxx
            - name: SPRING_AI_SILICONFLOW_BASE_URL
              value: https://api.siliconflow.cn
            - name: SPRING_AI_SILICONFLOW_CHAT_ENABLED
              value: "false"
            - name: SPRING_AI_SILICONFLOW_CHAT_OPTIONS_MODEL
              value: Qwen/QwQ-32B
            - name: SPRING_AI_SILICONFLOW_CHAT_OPTIONS_TEMPERATURE
              value: "0.7"
            - name: SPRING_AI_TENCENT_API_KEY
              value: sk-xxx
            - name: SPRING_AI_TENCENT_BASE_URL
              value: https://api.hunyuan.cloud.tencent.com
            - name: SPRING_AI_TENCENT_CHAT_ENABLED
              value: "false"
            - name: SPRING_AI_TENCENT_CHAT_OPTIONS_MODEL
              value: hunyuan-t1-latest
            - name: SPRING_AI_TENCENT_CHAT_OPTIONS_TEMPERATURE
              value: "0.7"
            - name: SPRING_AI_VECTORSTORE_ELASTICSEARCH_DIMENSIONS
              value: "1024"
            - name: SPRING_AI_VECTORSTORE_ELASTICSEARCH_ENABLED
              value: "true"
            - name: SPRING_AI_VECTORSTORE_ELASTICSEARCH_INDEX_NAME
              value: bytedesk_vs_index
            - name: SPRING_AI_VECTORSTORE_ELASTICSEARCH_INITIALIZE_SCHEMA
              value: "true"
            - name: SPRING_AI_VECTORSTORE_ELASTICSEARCH_SIMILARITY
              value: cosine
            - name: SPRING_AI_VECTORSTORE_REDIS_INDEX_NAME
              value: bytedesk_vs_index
            - name: SPRING_AI_VECTORSTORE_REDIS_INITIALIZE_SCHEMA
              value: "true"
            - name: SPRING_AI_VECTORSTORE_WEAVIATE_ENABLED
              value: "false"
            - name: SPRING_AI_VOLCENGINE_API_KEY
              value: sk-xxx
            - name: SPRING_AI_VOLCENGINE_BASE_URL
              value: https://ark.cn-beijing.volces.com/api/v3
            - name: SPRING_AI_VOLCENGINE_CHAT_ENABLED
              value: "false"
            - name: SPRING_AI_VOLCENGINE_CHAT_OPTIONS_MODEL
              value: doubao-1-5-pro-32k-250115
            - name: SPRING_AI_VOLCENGINE_CHAT_OPTIONS_TEMPERATURE
              value: "0.7"
            - name: SPRING_AI_ZHIPUAI_API_KEY
              value: sk-xxx
            - name: SPRING_AI_ZHIPUAI_CHAT_ENABLED
              value: "true"
            - name: SPRING_AI_ZHIPUAI_CHAT_OPTIONS_MAX_TOKENS
              value: "4096"
            - name: SPRING_AI_ZHIPUAI_CHAT_OPTIONS_MODEL
              value: glm-4-flash
            - name: SPRING_AI_ZHIPUAI_CHAT_OPTIONS_TEMPERATURE
              value: "0.7"
            - name: SPRING_AI_ZHIPUAI_CHAT_OPTIONS_TOP_P
              value: "0.9"
            - name: SPRING_AI_ZHIPUAI_CONNECTION_TIMEOUT
              value: "30"
            - name: SPRING_AI_ZHIPUAI_EMBEDDING_ENABLED
              value: "true"
            - name: SPRING_AI_ZHIPUAI_EMBEDDING_OPTIONS_MODEL
              value: embedding-2
            - name: SPRING_AI_ZHIPUAI_KEEP_ALIVE_DURATION
              value: "1"
            - name: SPRING_AI_ZHIPUAI_MAX_IDLE_CONNECTIONS
              value: "8"
            - name: SPRING_AI_ZHIPUAI_PING_INTERVAL
              value: "10"
            - name: SPRING_AI_ZHIPUAI_READ_TIMEOUT
              value: "10"
            - name: SPRING_AI_ZHIPUAI_WRITE_TIMEOUT
              value: "10"
            - name: SPRING_ARTEMIS_BROKER_URL
              value: tcp://artemis-bytedesk:61616
            - name: SPRING_ARTEMIS_EMBEDDED_QUEUES
              value: DLQ
            - name: SPRING_ARTEMIS_MODE
              value: native
            - name: SPRING_ARTEMIS_PASSWORD
              value: admin
            - name: SPRING_ARTEMIS_USER
              value: admin
            - name: SPRING_DATASOURCE_DRUID_STAT_VIEW_SERVLET_LOGIN_PASSWORD
              value: admin
            - name: SPRING_DATASOURCE_DRUID_STAT_VIEW_SERVLET_LOGIN_USERNAME
              value: admin@email.com
            - name: SPRING_DATASOURCE_PASSWORD
              value: r8FqfdbWUaN3
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-bytedesk:3306/bytedesk?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATA_REDIS_DATABASE
              value: "0"
            - name: SPRING_DATA_REDIS_HOST
              value: redis-bytedesk
            - name: SPRING_DATA_REDIS_PASSWORD
              value: qfRxz3tVT8Nh
            - name: SPRING_DATA_REDIS_PORT
              value: "6379"
            - name: SPRING_DATA_REDIS_REPOSITORIES_ENABLED
              value: "false"
            - name: SPRING_DATA_REDIS_TIMEOUT
              value: "10000"
            - name: SPRING_ELASTICSEARCH_PASSWORD
              value: bytedesk123
            - name: SPRING_ELASTICSEARCH_URIS
              value: http://elasticsearch-bytedesk:9200
            - name: SPRING_ELASTICSEARCH_USERNAME
              value: elastic
            - name: SPRING_JMS_LISTENER_ACKNOWLEDGE_MODE
              value: client
            - name: SPRING_JMS_LISTENER_AUTO_STARTUP
              value: "true"
            - name: SPRING_JMS_LISTENER_CONCURRENCY
              value: "1"
            - name: SPRING_JMS_LISTENER_INITIAL_INTERVAL
              value: "1000"
            - name: SPRING_JMS_LISTENER_MAX_ATTEMPTS
              value: "5"
            - name: SPRING_JMS_LISTENER_MAX_CONCURRENCY
              value: "10"
            - name: SPRING_JMS_LISTENER_MAX_INTERVAL
              value: "10000"
            - name: SPRING_JMS_LISTENER_MISSING_QUEUES_FATAL
              value: "false"
            - name: SPRING_JMS_LISTENER_MULTIPLIER
              value: "2"
            - name: SPRING_JMS_LISTENER_RECEIVE_TIMEOUT
              value: "1000"
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
            - name: SPRING_SECURITY_BASIC_ENABLED
              value: "true"
            - name: TZ
              value: Asia/Shanghai
            - name: WECHAT_PAY_CERTPATH
            - name: WECHAT_PAY_ENABLED
              value: "false"
          image: registry.cn-hangzhou.aliyuncs.com/bytedesk/bytedesk:latest
          name: bytedesk
          ports:
            - containerPort: 9003
              protocol: TCP
            - containerPort: 9885
              protocol: TCP
          volumeMounts:
            - mountPath: /app/uploads
              name: upload-data
      restartPolicy: Always
      volumes:
        - name: upload-data
          persistentVolumeClaim:
            claimName: upload-data
