apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: bytedesk-zipkin
  name: bytedesk-zipkin
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: bytedesk-zipkin
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.36.0 (HEAD)
      labels:
        io.kompose.service: bytedesk-zipkin
    spec:
      containers:
        - image: openzipkin/zipkin:latest
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://localhost:9411/health
            failureThreshold: 5
            periodSeconds: 30
            timeoutSeconds: 10
          name: zipkin-bytedesk
          ports:
            - containerPort: 9411
              protocol: TCP
          volumeMounts:
            - mountPath: /data
              name: zipkin-data
      restartPolicy: Always
      volumes:
        - name: zipkin-data
          persistentVolumeClaim:
            claimName: zipkin-data
