apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: bytedesk-redis
  name: bytedesk-redis
spec:
  ports:
    - name: "16379"
      port: 16379
      targetPort: 6379
  selector:
    io.kompose.service: bytedesk-redis
