apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: bytedesk-mysql
  name: bytedesk-mysql
spec:
  ports:
    - name: "13306"
      port: 13306
      targetPort: 3306
  selector:
    io.kompose.service: bytedesk-mysql
