apiVersion: apps/v1
kind: Deployment
metadata:
  name: bytedesk
  namespace: bytedesk
  labels:
    app: bytedesk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bytedesk
  template:
    metadata:
      labels:
        app: bytedesk
    spec:
      containers:
      - name: bytedesk
        image: registry.cn-hangzhou.aliyuncs.com/bytedesk/bytedesk:latest
        ports:
        - containerPort: 9003
          name: http
        - containerPort: 9885
          name: websocket
        env:
        # 基础配置
        - name: TZ
          value: "Asia/Shanghai"
        - name: SERVER_PORT
          value: "9003"
        
        # 微语配置
        - name: BYTEDESK_DEBUG
          value: "false"
        - name: BYTEDESK_VERSION
          value: "0.9.0"
        - name: BYTEDESK_LICENSE_KEY
          value: ""
        
        # 管理员配置
        - name: BYTEDESK_ADMIN_EMAIL
          value: "admin@email.com"
        - name: BYTEDESK_ADMIN_PASSWORD
          value: "admin"
        - name: BYTEDESK_ADMIN_NICKNAME
          value: "SuperAdmin"
        - name: BYTEDESK_ADMIN_MOBILE
          value: "13345678000"
        - name: BYTEDESK_ADMIN_VALIDATE_CODE
          value: "123456"
        
        # JWT 配置
        - name: BYTEDESK_JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: bytedesk-secrets
              key: jwt-secret-key
        - name: BYTEDESK_JWT_EXPIRATION
          value: "2592000000"
        
        # 数据库配置
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysql-service:3306/bytedesk?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true"
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: bytedesk-secrets
              key: mysql-username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bytedesk-secrets
              key: mysql-root-password
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: "update"
        
        # Redis 配置
        - name: SPRING_DATA_REDIS_HOST
          value: "redis-service"
        - name: SPRING_DATA_REDIS_PORT
          value: "6379"
        - name: SPRING_DATA_REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bytedesk-secrets
              key: redis-password
        
        # Elasticsearch 配置
        - name: SPRING_ELASTICSEARCH_URIS
          value: "http://elasticsearch-service:9200"
        - name: SPRING_ELASTICSEARCH_USERNAME
          valueFrom:
            secretKeyRef:
              name: bytedesk-secrets
              key: elasticsearch-username
        - name: SPRING_ELASTICSEARCH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bytedesk-secrets
              key: elasticsearch-password
        
        # Artemis 配置
        - name: SPRING_ARTEMIS_BROKER_URL
          value: "tcp://artemis-service:61616"
        - name: SPRING_ARTEMIS_USER
          valueFrom:
            secretKeyRef:
              name: bytedesk-secrets
              key: artemis-username
        - name: SPRING_ARTEMIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bytedesk-secrets
              key: artemis-password
        
        # AI 配置
        - name: SPRING_AI_MODEL_CHAT
          value: "zhipuai"
        - name: SPRING_AI_ZHIPUAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: bytedesk-secrets
              key: zhipuai-api-key
        - name: SPRING_AI_ZHIPUAI_CHAT_ENABLED
          value: "true"
        - name: SPRING_AI_ZHIPUAI_CHAT_OPTIONS_MODEL
          value: "glm-4-flash"
        
        volumeMounts:
        - name: uploads-data
          mountPath: /app/uploads
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 9003
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 9003
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: uploads-data
        persistentVolumeClaim:
          claimName: uploads-pvc 