apiVersion: apps/v1
kind: Deployment
metadata:
  name: bytedesk
  namespace: bytedesk
  labels:
    app: bytedesk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bytedesk
  template:
    metadata:
      labels:
        app: bytedesk
    spec:
      containers:
      - name: bytedesk
        image: registry.cn-hangzhou.aliyuncs.com/bytedesk/bytedesk:latest
        ports:
        - containerPort: 9003
          name: http
        - containerPort: 9885
          name: websocket
        env:
        # 基础配置
        - name: TZ
          value: "Asia/Shanghai"
        - name: SERVER_PORT
          value: "9003"
        
        # 微语配置
        - name: BYTEDESK_DEBUG
          value: "false"
        - name: BYTEDESK_VERSION
          value: "0.9.0"
        - name: BYTEDESK_LICENSE_KEY
          value: ""  # 请配置您的许可证密钥
        
        # 自定义配置
        - name: BYTEDESK_CUSTOM_ENABLED
          value: "false"
        - name: BYTEDESK_CUSTOM_NAME
          value: ""
        - name: BYTEDESK_CUSTOM_LOGO
          value: ""
        - name: BYTEDESK_CUSTOM_DESCRIPTION
          value: ""
        - name: BYTEDESK_CUSTOM_SHOW_RIGHT_CORNER_CHAT
          value: "false"
        - name: BYTEDESK_CUSTOM_SHOW_DEMO
          value: "false"
        - name: BYTEDESK_CUSTOM_PRIVACY_POLICY_URL
          value: "https://www.weiyuai.cn/privacy.html"
        - name: BYTEDESK_CUSTOM_TERMS_OF_SERVICE_URL
          value: "https://www.weiyuai.cn/terms.html"
        - name: BYTEDESK_CUSTOM_LOGIN_USERNAME_ENABLE
          value: "true"
        - name: BYTEDESK_CUSTOM_LOGIN_MOBILE_ENABLE
          value: "true"
        - name: BYTEDESK_CUSTOM_LOGIN_SCAN_ENABLE
          value: "true"
        - name: BYTEDESK_CUSTOM_DOC_URL_SHOW
          value: "true"
        - name: BYTEDESK_CUSTOM_DOC_URL
          value: "https://www.weiyuai.cn/docs/zh-CN/"
        - name: BYTEDESK_CUSTOM_LANG
          value: "zh-CN"
        - name: BYTEDESK_CUSTOM_ALLOW_REGISTER
          value: "true"
        - name: BYTEDESK_CUSTOM_FORCE_VALIDATE_MOBILE
          value: "true"
        - name: BYTEDESK_CUSTOM_FORCE_VALIDATE_EMAIL
          value: "true"
        
        # 管理员配置
        - name: BYTEDESK_ADMIN_EMAIL
          value: "admin@email.com"
        - name: BYTEDESK_ADMIN_PASSWORD
          value: "admin"
        - name: BYTEDESK_ADMIN_NICKNAME
          value: "SuperAdmin"
        - name: BYTEDESK_ADMIN_MOBILE
          value: "13345678000"
        - name: BYTEDESK_ADMIN_MOBILE_WHITELIST
          value: "18888888000,18888888001,18888888002,18888888003,18888888004,18888888005"
        - name: BYTEDESK_ADMIN_EMAIL_WHITELIST
          value: "100@email.com,101@email.com,102@email.com,103@email.com,104@email.com,105@email.com"
        - name: BYTEDESK_ADMIN_VALIDATE_CODE
          value: "123456"
        
        # 成员配置
        - name: BYTEDESK_MEMBER_PASSWORD
          value: "123456"
        
        # 组织配置
        - name: BYTEDESK_ORGANIZATION_NAME
          value: "MyCompany"
        - name: BYTEDESK_ORGANIZATION_CODE
          value: "bytedesk"
        
        # 功能配置
        - name: BYTEDESK_FEATURES_JAVA_AI
          value: "true"
        - name: BYTEDESK_FEATURES_EMAIL_TYPE
          value: "javamail"
        - name: BYTEDESK_FEATURES_AVATAR_BASE_URL
          value: "http://bytedesk-service:9003"
        
        # JWT 配置
        - name: BYTEDESK_JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: bytedesk-secrets
              key: jwt-secret-key
        - name: BYTEDESK_JWT_EXPIRATION
          value: "2592000000"
        - name: BYTEDESK_JWT_REFRESH_TOKEN_EXPIRATION
          value: "5184000000"
        
        # 数据库配置
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysql-service:3306/bytedesk?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true"
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: bytedesk-secrets
              key: mysql-username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bytedesk-secrets
              key: mysql-root-password
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: "update"
        
        # Redis 配置
        - name: SPRING_DATA_REDIS_DATABASE
          value: "0"
        - name: SPRING_DATA_REDIS_HOST
          value: "redis-service"
        - name: SPRING_DATA_REDIS_PORT
          value: "6379"
        - name: SPRING_DATA_REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bytedesk-secrets
              key: redis-password
        - name: SPRING_DATA_REDIS_TIMEOUT
          value: "10000"
        - name: SPRING_DATA_REDIS_REPOSITORIES_ENABLED
          value: "false"
        
        # 缓存配置
        - name: BYTEDESK_CACHE_LEVEL
          value: "0"
        - name: BYTEDESK_CACHE_PREFIX
          value: "bytedeskim"
        - name: BYTEDESK_CACHE_REDIS_STREAM_KEY
          value: "bytedeskim:stream"
        
        # 文件上传配置
        - name: BYTEDESK_UPLOAD_TYPE
          value: "local"
        - name: BYTEDESK_UPLOAD_DIR
          value: "/app/uploads"
        - name: BYTEDESK_UPLOAD_URL
          value: "http://bytedesk-service:9003"
        
        # MinIO 配置
        - name: BYTEDESK_MINIO_ENABLED
          value: "false"
        - name: BYTEDESK_MINIO_ENDPOINT
          value: "http://minio-service:9000"
        - name: BYTEDESK_MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: bytedesk-secrets
              key: minio-access-key
        - name: BYTEDESK_MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: bytedesk-secrets
              key: minio-secret-key
        - name: BYTEDESK_MINIO_BUCKET_NAME
          value: "bytedesk"
        - name: BYTEDESK_MINIO_REGION
          value: "us-east-1"
        - name: BYTEDESK_MINIO_SECURE
          value: "false"
        
        # 知识库配置
        - name: BYTEDESK_KBASE_THEME
          value: "default"
        - name: BYTEDESK_KBASE_HTML_PATH
          value: "helpcenter"
        - name: BYTEDESK_KBASE_API_URL
          value: "http://bytedesk-service:9003"
        
        # WebSocket 配置
        - name: BYTEDESK_SOCKET_HOST
          value: "0.0.0.0"
        - name: BYTEDESK_SOCKET_WEBSOCKET_PORT
          value: "9885"
        - name: BYTEDESK_SOCKET_LEAK_DETECTOR_LEVEL
          value: "SIMPLE"
        - name: BYTEDESK_SOCKET_PARENT_EVENT_LOOP_GROUP_THREAD_COUNT
          value: "1"
        - name: BYTEDESK_SOCKET_CHILD_EVENT_LOOP_GROUP_THREAD_COUNT
          value: "8"
        - name: BYTEDESK_SOCKET_MAX_PAYLOAD_SIZE
          value: "10240"
        
        # 集群配置
        - name: BYTEDESK_CLUSTER_ENABLED
          value: "false"
        
        # Elasticsearch 配置
        - name: SPRING_ELASTICSEARCH_URIS
          value: "http://elasticsearch-service:9200"
        - name: SPRING_ELASTICSEARCH_USERNAME
          valueFrom:
            secretKeyRef:
              name: bytedesk-secrets
              key: elasticsearch-username
        - name: SPRING_ELASTICSEARCH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bytedesk-secrets
              key: elasticsearch-password
        - name: SPRING_AI_VECTORSTORE_ELASTICSEARCH_ENABLED
          value: "true"
        - name: SPRING_AI_VECTORSTORE_ELASTICSEARCH_INITIALIZE_SCHEMA
          value: "true"
        - name: SPRING_AI_VECTORSTORE_ELASTICSEARCH_INDEX_NAME
          value: "bytedesk_vs_index"
        - name: SPRING_AI_VECTORSTORE_ELASTICSEARCH_DIMENSIONS
          value: "1024"
        - name: SPRING_AI_VECTORSTORE_ELASTICSEARCH_SIMILARITY
          value: "cosine"
        
        # Artemis JMS 配置
        - name: SPRING_ARTEMIS_MODE
          value: "native"
        - name: SPRING_ARTEMIS_BROKER_URL
          value: "tcp://artemis-service:61616"
        - name: SPRING_ARTEMIS_USER
          valueFrom:
            secretKeyRef:
              name: bytedesk-secrets
              key: artemis-username
        - name: SPRING_ARTEMIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bytedesk-secrets
              key: artemis-password
        - name: SPRING_JMS_LISTENER_CONCURRENCY
          value: "1"
        - name: SPRING_JMS_LISTENER_MAX_CONCURRENCY
          value: "10"
        - name: SPRING_JMS_LISTENER_ACKNOWLEDGE_MODE
          value: "client"
        - name: SPRING_JMS_LISTENER_AUTO_STARTUP
          value: "true"
        - name: SPRING_JMS_LISTENER_MAX_ATTEMPTS
          value: "5"
        - name: SPRING_JMS_LISTENER_INITIAL_INTERVAL
          value: "1000"
        - name: SPRING_JMS_LISTENER_MAX_INTERVAL
          value: "10000"
        - name: SPRING_JMS_LISTENER_MULTIPLIER
          value: "2.0"
        - name: SPRING_JMS_LISTENER_RECEIVE_TIMEOUT
          value: "1000"
        - name: SPRING_ARTEMIS_EMBEDDED_QUEUES
          value: "DLQ"
        - name: SPRING_JMS_LISTENER_MISSING_QUEUES_FATAL
          value: "false"
        
        # AI 模型配置
        - name: SPRING_AI_MODEL_CHAT
          value: "zhipuai"
        - name: SPRING_AI_MODEL_EMBEDDING
          value: "zhipuai"
        - name: SPRING_AI_MODEL_VISION
          value: "zhipuai"
        - name: SPRING_AI_MODEL_AUDIO
          value: "zhipuai"
        - name: SPRING_AI_MODEL_RERANK
          value: "dashscope"
        
        # 智谱AI配置
        - name: SPRING_AI_ZHIPUAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: bytedesk-secrets
              key: zhipuai-api-key
        - name: SPRING_AI_ZHIPUAI_CHAT_ENABLED
          value: "true"
        - name: SPRING_AI_ZHIPUAI_CHAT_OPTIONS_MODEL
          value: "glm-4-flash"
        - name: SPRING_AI_ZHIPUAI_CHAT_OPTIONS_TEMPERATURE
          value: "0.7"
        - name: SPRING_AI_ZHIPUAI_CHAT_OPTIONS_TOP_P
          value: "0.9"
        - name: SPRING_AI_ZHIPUAI_CHAT_OPTIONS_MAX_TOKENS
          value: "4096"
        - name: SPRING_AI_ZHIPUAI_CONNECTION_TIMEOUT
          value: "30"
        - name: SPRING_AI_ZHIPUAI_READ_TIMEOUT
          value: "10"
        - name: SPRING_AI_ZHIPUAI_WRITE_TIMEOUT
          value: "10"
        - name: SPRING_AI_ZHIPUAI_PING_INTERVAL
          value: "10"
        - name: SPRING_AI_ZHIPUAI_MAX_IDLE_CONNECTIONS
          value: "8"
        - name: SPRING_AI_ZHIPUAI_KEEP_ALIVE_DURATION
          value: "1"
        - name: SPRING_AI_ZHIPUAI_EMBEDDING_ENABLED
          value: "true"
        - name: SPRING_AI_ZHIPUAI_EMBEDDING_OPTIONS_MODEL
          value: "embedding-2"
        
        # 其他AI提供商配置（默认禁用）
        - name: SPRING_AI_OPENAI_CHAT_ENABLED
          value: "false"
        - name: SPRING_AI_DEEPSEEK_CHAT_ENABLED
          value: "false"
        - name: SPRING_AI_DASHSCOPE_ENABLED
          value: "false"
        - name: SPRING_AI_SILICONFLOW_CHAT_ENABLED
          value: "false"
        - name: SPRING_AI_GITEE_CHAT_ENABLED
          value: "false"
        - name: SPRING_AI_TENCENT_CHAT_ENABLED
          value: "false"
        - name: SPRING_AI_BAIDU_CHAT_ENABLED
          value: "false"
        - name: SPRING_AI_VOLCENGINE_CHAT_ENABLED
          value: "false"
        
        # 数据库连接池配置
        - name: SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT
          value: "60000"
        - name: SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE
          value: "10"
        
        # Druid 配置
        - name: SPRING_DATASOURCE_DRUID_STAT_VIEW_SERVLET_LOGIN_USERNAME
          value: "admin@email.com"
        - name: SPRING_DATASOURCE_DRUID_STAT_VIEW_SERVLET_LOGIN_PASSWORD
          value: "admin"
        
        # Actuator 配置
        - name: MANAGEMENT_ENDPOINTS_ENABLED_BY_DEFAULT
          value: "false"
        - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
          value: ""
        - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_EXCLUDE
          value: "*"
        - name: MANAGEMENT_ENDPOINT_HEALTH_ENABLED
          value: "false"
        - name: MANAGEMENT_ENDPOINT_INFO_ENABLED
          value: "false"
        - name: MANAGEMENT_SERVER_PORT
          value: "-1"
        - name: MANAGEMENT_ENDPOINTS_WEB_BASE_PATH
          value: "/management"
        - name: SPRING_SECURITY_BASIC_ENABLED
          value: "true"
        
        # 分布式追踪配置
        - name: MANAGEMENT_TRACING_ENABLED
          value: "false"
        - name: MANAGEMENT_ZIPKIN_TRACING_ENABLED
          value: "false"
        - name: MANAGEMENT_TRACING_SAMPLING_PROBABILITY
          value: "0.0"
        
        # 文档配置
        - name: SPRINGDOC_SHOW_ACTUATOR
          value: "false"
        - name: SPRINGDOC_SWAGGER_UI_ENABLED
          value: "true"
        - name: SPRINGDOC_SWAGGER_UI_PATH
          value: "/index.html"
        - name: SPRINGDOC_API_DOCS_ENABLED
          value: "true"
        - name: SPRINGDOC_API_DOCS_PATH
          value: "/v3/api-docs"
        - name: KNIFE4J_ENABLED
          value: "true"
        - name: KNIFE4J_SETTING_LANGUAGE
          value: "zh_cn"
        
        # 日志配置
        - name: LOGGING_LEVEL_COM_BYTEDESK_AI
          value: "DEBUG"
        - name: LOGGING_LEVEL_COM_BYTEDESK_CORE
          value: "DEBUG"
        - name: LOGGING_LEVEL_COM_BYTEDESK_KBASE
          value: "DEBUG"
        - name: LOGGING_LEVEL_COM_BYTEDESK_SERVICE
          value: "DEBUG"
        - name: LOGGING_LEVEL_COM_BYTEDESK_SOCIAL
          value: "DEBUG"
        - name: LOGGING_LEVEL_COM_BYTEDESK_WECHAT
          value: "DEBUG"
        - name: LOGGING_LEVEL_COM_BYTEDESK_SHOP
          value: "DEBUG"
        - name: LOGGING_LEVEL_COM_BYTEDESK_TEAM
          value: "DEBUG"
        - name: LOGGING_LEVEL_COM_BYTEDESK_TICKET
          value: "DEBUG"
        - name: LOGGING_LEVEL_COM_BYTEDESK_STARTER
          value: "DEBUG"
        
        volumeMounts:
        - name: uploads-data
          mountPath: /app/uploads
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 9003
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 9003
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: uploads-data
        persistentVolumeClaim:
          claimName: uploads-pvc 