apiVersion: v1
kind: ConfigMap
metadata:
  name: bytedesk-config
  namespace: bytedesk
data:
  # 基础配置
  TZ: "Asia/Shanghai"
  SERVER_PORT: "9003"
  
  # 微语配置
  BYTEDESK_DEBUG: "false"
  BYTEDESK_VERSION: "0.9.6"
  BYTEDESK_LICENSE_KEY: ""
  
  # 自定义配置
  BYTEDESK_CUSTOM_ENABLED: "false"
  BYTEDESK_CUSTOM_NAME: ""
  BYTEDESK_CUSTOM_LOGO: ""
  BYTEDESK_CUSTOM_DESCRIPTION: ""
  BYTEDESK_CUSTOM_SHOW_RIGHT_CORNER_CHAT: "false"
  BYTEDESK_CUSTOM_SHOW_DEMO: "false"
  BYTEDESK_CUSTOM_PRIVACY_POLICY_URL: "https://www.weiyuai.cn/privacy.html"
  BYTEDESK_CUSTOM_TERMS_OF_SERVICE_URL: "https://www.weiyuai.cn/terms.html"
  BYTEDESK_CUSTOM_LOGIN_USERNAME_ENABLE: "true"
  BYTEDESK_CUSTOM_LOGIN_MOBILE_ENABLE: "true"
  BYTEDESK_CUSTOM_LOGIN_SCAN_ENABLE: "true"
  BYTEDESK_CUSTOM_DOC_URL_SHOW: "true"
  BYTEDESK_CUSTOM_DOC_URL: "https://www.weiyuai.cn/docs/zh-CN/"
  BYTEDESK_CUSTOM_LANG: "zh-CN"
  BYTEDESK_CUSTOM_ALLOW_REGISTER: "true"
  BYTEDESK_CUSTOM_FORCE_VALIDATE_MOBILE: "true"
  BYTEDESK_CUSTOM_FORCE_VALIDATE_EMAIL: "true"
  
  # 管理员配置
  BYTEDESK_ADMIN_EMAIL: "admin@email.com"
  BYTEDESK_ADMIN_PASSWORD: "admin"
  BYTEDESK_ADMIN_NICKNAME: "SuperAdmin"
  BYTEDESK_ADMIN_MOBILE: "13345678000"
  BYTEDESK_ADMIN_VALIDATE_CODE: "123456"
  
  # 管理员白名单配置
  BYTEDESK_ADMIN_MOBILE_WHITELIST: "18888888000,18888888001,18888888002,18888888003,18888888004,18888888005"
  BYTEDESK_ADMIN_EMAIL_WHITELIST: "100@email.com,101@email.com,102@email.com,103@email.com,104@email.com,105@email.com"
  
  # 会员配置
  BYTEDESK_MEMBER_PASSWORD: "123456"
  
  # 性能测试配置
  BYTEDESK_TESTING_ENABLED: "false"
  BYTEDESK_TESTING_DISABLE_CAPTCHA: "false"
  BYTEDESK_TESTING_DISABLE_IP_FILTER: "false"
  
  # 组织配置
  BYTEDESK_ORGANIZATION_NAME: "MyCompany"
  BYTEDESK_ORGANIZATION_CODE: "bytedesk"
  
  # 功能配置
  BYTEDESK_FEATURES_JAVA_AI: "true"
  BYTEDESK_FEATURES_EMAIL_TYPE: "javamail"
  BYTEDESK_FEATURES_AVATAR_BASE_URL: "http://127.0.0.1:9003"
  
  # CORS 配置
  BYTEDESK_CORS_ALLOWED_ORIGINS: "*"
  
  # JWT 配置
  BYTEDESK_JWT_EXPIRATION: "2592000000"
  BYTEDESK_JWT_REFRESH_TOKEN_EXPIRATION: "5184000000"
  
  # 数据库配置
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-service:3306/bytedesk?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true"
  
  # 数据库连接池配置
  SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT: "60000"
  SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: "10"
  
  # Druid 配置
  SPRING_DATASOURCE_DRUID_STAT_VIEW_SERVLET_LOGIN_USERNAME: "admin@email.com"
  SPRING_DATASOURCE_DRUID_STAT_VIEW_SERVLET_LOGIN_PASSWORD: "admin"
  
  # Actuator 配置
  MANAGEMENT_ENDPOINTS_ENABLED_BY_DEFAULT: "false"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: ""
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_EXCLUDE: "*"
  MANAGEMENT_ENDPOINT_HEALTH_ENABLED: "false"
  MANAGEMENT_ENDPOINT_INFO_ENABLED: "false"
  MANAGEMENT_ENDPOINTS_WEB_BASE_PATH: "/management"
  
  # Zipkin 追踪配置
  MANAGEMENT_TRACING_ENABLED: "false"
  MANAGEMENT_TRACING_SAMPLING_PROBABILITY: "0.0"
  
  # Spring Security 配置
  SPRING_SECURITY_BASIC_ENABLED: "true"
  
  # 微信支付配置
  WECHAT_PAY_ENABLED: "false"
  WECHAT_PAY_CERTPATH: ""
  
  # 阿里云短信配置
  ALIYUN_SMS_SIGNNAME: ""
  ALIYUN_SMS_TEMPLATECODE: ""
  
  # Redis 配置
  SPRING_DATA_REDIS_DATABASE: "0"
  SPRING_DATA_REDIS_HOST: "redis-service"
  SPRING_DATA_REDIS_PORT: "6379"
  SPRING_DATA_REDIS_TIMEOUT: "10000"
  SPRING_DATA_REDIS_REPOSITORIES_ENABLED: "false"
  
  # 缓存配置
  BYTEDESK_CACHE_LEVEL: "0"
  BYTEDESK_CACHE_PREFIX: "bytedeskim"
  BYTEDESK_CACHE_REDIS_STREAM_KEY: "bytedeskim:stream"
  
  # 上传配置
  BYTEDESK_UPLOAD_TYPE: "local"
  BYTEDESK_UPLOAD_DIR: "/app/uploads"
  BYTEDESK_UPLOAD_URL: "http://127.0.0.1:9003"
  
  # 知识库配置
  BYTEDESK_KBASE_THEME: "default"
  BYTEDESK_KBASE_HTML_PATH: "helpcenter"
  BYTEDESK_KBASE_API_URL: "http://127.0.0.1:9003"
  
  # Socket 配置
  BYTEDESK_SOCKET_HOST: "0.0.0.0"
  BYTEDESK_SOCKET_WEBSOCKET_PORT: "9885"
  BYTEDESK_SOCKET_LEAK_DETECTOR_LEVEL: "SIMPLE"
  BYTEDESK_SOCKET_PARENT_EVENT_LOOP_GROUP_THREAD_COUNT: "1"
  BYTEDESK_SOCKET_CHILD_EVENT_LOOP_GROUP_THREAD_COUNT: "8"
  BYTEDESK_SOCKET_MAX_PAYLOAD_SIZE: "10240"
  
  # 集群配置
  BYTEDESK_CLUSTER_ENABLED: "false"
  
  # 日志配置
  LOGGING_LEVEL_COM_BYTEDESK_AI: "DEBUG"
  LOGGING_LEVEL_COM_BYTEDESK_CORE: "DEBUG"
  LOGGING_LEVEL_COM_BYTEDESK_KBASE: "DEBUG"
  LOGGING_LEVEL_COM_BYTEDESK_SERVICE: "DEBUG"
  LOGGING_LEVEL_COM_BYTEDESK_SOCIAL: "DEBUG"
  LOGGING_LEVEL_COM_BYTEDESK_WECHAT: "DEBUG"
  LOGGING_LEVEL_COM_BYTEDESK_SHOP: "DEBUG"
  LOGGING_LEVEL_COM_BYTEDESK_TEAM: "DEBUG"
  LOGGING_LEVEL_COM_BYTEDESK_TICKET: "DEBUG"
  LOGGING_LEVEL_COM_BYTEDESK_STARTER: "DEBUG"
  
  # Swagger 配置
  SPRINGDOC_SHOW_ACTUATOR: "false"
  SPRINGDOC_SWAGGER_UI_ENABLED: "true"
  SPRINGDOC_SWAGGER_UI_PATH: "/index.html"
  SPRINGDOC_API_DOCS_ENABLED: "true"
  SPRINGDOC_API_DOCS_PATH: "/v3/api-docs"
  KNIFE4J_ENABLED: "true"
  
  # Elasticsearch 配置
  SPRING_ELASTICSEARCH_URIS: "http://elasticsearch-service:9200"
  
  # Elasticsearch 向量存储配置
  SPRING_AI_VECTORSTORE_ELASTICSEARCH_ENABLED: "true"
  SPRING_AI_VECTORSTORE_ELASTICSEARCH_INITIALIZE_SCHEMA: "true"
  SPRING_AI_VECTORSTORE_ELASTICSEARCH_INDEX_NAME: "bytedesk_vs_index"
  SPRING_AI_VECTORSTORE_ELASTICSEARCH_DIMENSIONS: "1024"
  SPRING_AI_VECTORSTORE_ELASTICSEARCH_SIMILARITY: "cosine"
  
  # Artemis 配置
  SPRING_ARTEMIS_MODE: "native"
  SPRING_ARTEMIS_BROKER_URL: "tcp://artemis-service:61616"
  
  # JMS 配置
  SPRING_JMS_LISTENER_CONCURRENCY: "1"
  SPRING_JMS_LISTENER_MAX_CONCURRENCY: "10"
  SPRING_JMS_LISTENER_ACKNOWLEDGE_MODE: "client"
  SPRING_JMS_LISTENER_AUTO_STARTUP: "true"
  SPRING_JMS_LISTENER_MAX_ATTEMPTS: "5"
  SPRING_JMS_LISTENER_INITIAL_INTERVAL: "1000"
  SPRING_JMS_LISTENER_MAX_INTERVAL: "10000"
  SPRING_JMS_LISTENER_MULTIPLIER: "2.0"
  SPRING_JMS_LISTENER_RECEIVE_TIMEOUT: "1000"
  SPRING_JMS_LISTENER_MISSING_QUEUES_FATAL: "false"
  SPRING_ARTEMIS_EMBEDDED_QUEUES: "DLQ"
  
  # Zipkin 配置
  MANAGEMENT_ZIPKIN_TRACING_ENABLED: "false"
  MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: "http://zipkin-service:9411/api/v2/spans"
  
  # MinIO 配置
  BYTEDESK_MINIO_ENABLED: "false"
  BYTEDESK_MINIO_ENDPOINT: "http://minio-service:9000"
  BYTEDESK_MINIO_BUCKET_NAME: "bytedesk"
  BYTEDESK_MINIO_REGION: "us-east-1"
  BYTEDESK_MINIO_SECURE: "false"
  
  # 推送配置
  BYTEDESK_PUSH_APNS_BUNDLE_ID: "com.kefux.im"
  BYTEDESK_PUSH_APNS_P12_URL: "123.p12"
  BYTEDESK_PUSH_APNS_P12_PASSWORD: "123456"
  
  # AI 配置
  SPRING_AI_MODEL_CHAT: "zhipuai"
  SPRING_AI_MODEL_EMBEDDING: "zhipuai"
  SPRING_AI_MODEL_VISION: "zhipuai"
  SPRING_AI_MODEL_AUDIO: "zhipuai"
  SPRING_AI_MODEL_RERANK: "dashscope"
  
  # ZhipuAI 配置
  SPRING_AI_ZHIPUAI_CHAT_ENABLED: "true"
  SPRING_AI_ZHIPUAI_CHAT_OPTIONS_MODEL: "glm-4-flash"
  SPRING_AI_ZHIPUAI_CHAT_OPTIONS_TEMPERATURE: "0.7"
  SPRING_AI_ZHIPUAI_CHAT_OPTIONS_TOP_P: "0.9"
  SPRING_AI_ZHIPUAI_CHAT_OPTIONS_MAX_TOKENS: "4096"
  SPRING_AI_ZHIPUAI_CONNECTION_TIMEOUT: "30"
  SPRING_AI_ZHIPUAI_READ_TIMEOUT: "10"
  SPRING_AI_ZHIPUAI_WRITE_TIMEOUT: "10"
  SPRING_AI_ZHIPUAI_PING_INTERVAL: "10"
  SPRING_AI_ZHIPUAI_MAX_IDLE_CONNECTIONS: "8"
  SPRING_AI_ZHIPUAI_KEEP_ALIVE_DURATION: "1"
  SPRING_AI_ZHIPUAI_EMBEDDING_ENABLED: "true"
  SPRING_AI_ZHIPUAI_EMBEDDING_OPTIONS_MODEL: "embedding-2"
  
  # Ollama 配置
  SPRING_AI_OLLAMA_BASE_URL: "http://host.docker.internal:11434"
  SPRING_AI_OLLAMA_CHAT_ENABLED: "false"
  SPRING_AI_OLLAMA_CHAT_OPTIONS_MODEL: "qwen3:0.6b"
  SPRING_AI_OLLAMA_CHAT_OPTIONS_TEMPERATURE: "0.7"
  SPRING_AI_OLLAMA_EMBEDDING_ENABLED: "false"
  SPRING_AI_OLLAMA_EMBEDDING_OPTIONS_MODEL: "bge-m3:latest"
  SPRING_AI_OLLAMA_INIT_PULL_MODEL_STRATEGY: "when_missing"
  SPRING_AI_OLLAMA_EMBEDDING_OPTIONS_MODEL_RERANK: "bge-reranker-v2-m3:latest"
  
  # DeepSeek 配置
  SPRING_AI_DEEPSEEK_BASE_URL: "https://api.deepseek.com"
  SPRING_AI_DEEPSEEK_CHAT_ENABLED: "false"
  SPRING_AI_DEEPSEEK_CHAT_OPTIONS_MODEL: "deepseek-chat"
  SPRING_AI_DEEPSEEK_CHAT_OPTIONS_TEMPERATURE: "0.7"
  SPRING_AI_DEEPSEEK_EMBEDDING_ENABLED: "false"
  
  # OpenAI 配置
  SPRING_AI_OPENAI_BASE_URL: "https://api.openai.com"
  SPRING_AI_OPENAI_CHAT_ENABLED: "false"
  SPRING_AI_OPENAI_CHAT_OPTIONS_MODEL: "gpt-4o"
  SPRING_AI_OPENAI_CHAT_OPTIONS_TEMPERATURE: "0.7"
  SPRING_AI_OPENAI_EMBEDDING_ENABLED: "false"
  
  # 阿里云百炼配置
  SPRING_AI_DASHSCOPE_ENABLED: "false"
  SPRING_AI_DASHSCOPE_BASE_URL: "https://dashscope.aliyuncs.com"
  SPRING_AI_DASHSCOPE_CHAT_ENABLED: "false"
  SPRING_AI_DASHSCOPE_CHAT_OPTIONS_MODEL: "qwen-max"
  SPRING_AI_DASHSCOPE_CHAT_OPTIONS_TEMPERATURE: "0.7"
  SPRING_AI_DASHSCOPE_CHAT_OPTIONS_TOP_P: "3"
  SPRING_AI_DASHSCOPE_AUDIO_TRANSCRIPTION_ENABLED: "false"
  SPRING_AI_DASHSCOPE_IMAGE_ENABLED: "false"
  SPRING_AI_DASHSCOPE_EMBEDDING_ENABLED: "false"
  SPRING_AI_DASHSCOPE_EMBEDDING_OPTIONS_MODEL: "text-embedding-v1"
  SPRING_AI_DASHSCOPE_AUDIO_SYNTHESIS_ENABLED: "false"
  
  # SiliconFlow 配置
  SPRING_AI_SILICONFLOW_BASE_URL: "https://api.siliconflow.cn"
  SPRING_AI_SILICONFLOW_CHAT_ENABLED: "false"
  SPRING_AI_SILICONFLOW_CHAT_OPTIONS_MODEL: "Qwen/QwQ-32B"
  SPRING_AI_SILICONFLOW_CHAT_OPTIONS_TEMPERATURE: "0.7"
  
  # Gitee 配置
  SPRING_AI_GITEE_BASE_URL: "https://ai.gitee.com"
  SPRING_AI_GITEE_CHAT_ENABLED: "false"
  SPRING_AI_GITEE_CHAT_OPTIONS_MODEL: "Qwen/QwQ-32B"
  SPRING_AI_GITEE_CHAT_OPTIONS_TEMPERATURE: "0.7"
  
  # 腾讯配置
  SPRING_AI_TENCENT_BASE_URL: "https://api.hunyuan.cloud.tencent.com"
  SPRING_AI_TENCENT_CHAT_ENABLED: "false"
  SPRING_AI_TENCENT_CHAT_OPTIONS_MODEL: "hunyuan-t1-latest"
  SPRING_AI_TENCENT_CHAT_OPTIONS_TEMPERATURE: "0.7"
  
  # 百度配置
  SPRING_AI_BAIDU_BASE_URL: "https://qianfan.baidubce.com/v2"
  SPRING_AI_BAIDU_CHAT_ENABLED: "false"
  SPRING_AI_BAIDU_CHAT_OPTIONS_MODEL: "ernie-x1-32k-preview"
  SPRING_AI_BAIDU_CHAT_OPTIONS_TEMPERATURE: "0.7"
  
  # 火山引擎配置
  SPRING_AI_VOLCENGINE_BASE_URL: "https://ark.cn-beijing.volces.com/api/v3"
  SPRING_AI_VOLCENGINE_CHAT_ENABLED: "false"
  SPRING_AI_VOLCENGINE_CHAT_OPTIONS_MODEL: "doubao-1-5-pro-32k-250115"
  SPRING_AI_VOLCENGINE_CHAT_OPTIONS_TEMPERATURE: "0.7"
  
  # 向量存储配置
  SPRING_AI_VECTORSTORE_REDIS_INITIALIZE_SCHEMA: "true"
  SPRING_AI_VECTORSTORE_REDIS_INDEX_NAME: "bytedesk_vs_index"
  
  # MCP 配置
  SPRING_AI_MCP_CLIENT_ENABLED: "false"
  SPRING_AI_MCP_SERVER_ENABLED: "false"
  SPRING_AI_MCP_SERVER_STDIO: "false"
  SPRING_AI_MCP_SERVER_TYPE: "SYNC"
  
  # Weaviate 配置
  SPRING_AI_VECTORSTORE_WEAVIATE_ENABLED: "false" 