---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: activemq
  namespace: ykf
  labels:
    app: activemq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: activemq
  template:
    metadata:
      labels:
        app: activemq
    spec:
      containers:
      - name: activemq
        image: easzlab.io.local:5000/dev/activemq-artemis
        env:
        - name: ARTEMIS_USER
          value: "admin"
        - name: ARTEMIS_PASSWORD
          value: "admin"
        - name: ANONYMOUS_LOGIN
          value: "false"
        - name: EXTRA_ARGS
          value: "--http-host 0.0.0.0 --relax-jolokia"
        ports:
        - containerPort: 61616  # Core protocol
        - containerPort: 5672   # AMQP
        - containerPort: 1883   # MQTT
        - containerPort: 8161   # Web console
---
apiVersion: v1
kind: Service
metadata:
  name: activemq
  namespace: ykf
spec:
  selector:
    app: activemq
  ports:
    - name: core
      port: 61616
      targetPort: 61616
    - name: amqp
      port: 5672
      targetPort: 5672
    - name: mqtt
      port: 1883
      targetPort: 1883
    - name: web
      port: 8161
      targetPort: 8161
