---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch8-ykf-pv
  namespace: ykf
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /data/pv/ykfelasticsearch8
    server: 192.168.48.70
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch8-ykf-pvc
  namespace: ykf
spec:
  volumeName: elasticsearch8-ykf-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
