---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch8
  namespace: ykf
spec:
  selector:
    matchLabels:
      app: elasticsearch8
  template:
    metadata:
      labels:
        app: elasticsearch8
        name: elasticsearch8
    spec:
      containers:
      - name: elasticsearch8
        image: easzlab.io.local:5000/dev/elasticsearch:8.18.0
        env:
        - name: node.name
          value: es01
        - name: cluster.name
          value: es-cluster
        - name: discovery.type
          value: single-node
        - name: bootstrap.memory_lock
          value: "true"
        - name: ES_JAVA_OPTS
          value: -Xms512m -Xmx512m
        - name: xpack.security.enabled
          value: "true"
        - name: ELASTIC_PASSWORD
          value: ykfsft20250805
        - name: network.host
          value: "0.0.0.0"
        - name: http.host
          value: "0.0.0.0"
        - name: transport.host
          value: "0.0.0.0"
        ports:
        - containerPort: 9200
          name: http
        - containerPort: 9300
          name: transport
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data
        resources:
          limits:
            memory: 1Gi
          requests:
            memory: 512Mi
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: elasticsearch8-ykf-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch8
  namespace: ykf
  labels:
    name: elasticsearch8
spec:
  ports:
  - name:  web-9200
    port: 9200
    targetPort: 9200
    protocol: TCP
  - name:  web-9300
    port: 9300
    targetPort: 9300
    protocol: TCP
  selector:
    name: elasticsearch8
