---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: ykf
spec:
  replicas: 1
  serviceName: mysql
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: easzlab.io.local:5000/dev/mysql:8.0.32
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "mssql@admin2025"
            - name: MYSQL_PASSWORD
              value: "mssql@admin2025"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
            #- mountPath: /etc/my.cnf
              #name: mycnf
              #subPath: my.cnf
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
           claimName: mysql2-pvc          
        - name: mycnf
          configMap:
            name: mysql-config
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: ykf
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
