---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql2-pv
  namespace: ykf
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /data/pv/ykfmysql
    server: 192.168.48.70
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql2-pvc
  namespace: ykf
spec:
  volumeName: mysql2-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
