---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: ykf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: easzlab.io.local:5000/dev/redis:6.0.20
        command: ["sh","-c","redis-server --requirepass 123456"]
        ports:
        - containerPort: 6379
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
          limits:
            cpu: "500m"
            memory: "200Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: ykf
spec:
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379
