---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ykfcore
  namespace: ykf
  labels:
    app: ykfcore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ykfcore
  template:
    metadata:
      labels:
        app: ykfcore
    spec:
      containers:
      - name: ykfcore
        image: easzlab.io.local:5000/dev/ykfcore:20250707
        imagePullPolicy: Always
        env:
        # 基本配置
        - name: SERVER_PORT
          value: "9003"        
        # bytedesk 配置
        - name: BYTEDESK_DEBUG
          value: "true"
        - name: BYTEDESK_VERSION
          value: "0.8.6"
        - name: BYTEDESK_APPKEY
          value: "cDoyMDI1LTA5LTA2OlBMQVRGT1JNOjo6Og=="        
        # 自定义配置
        - name: BYTEDESK_CUSTOM_ENABLED
          value: "true"
        - name: BYTEDESK_CUSTOM_NAME
          value: "k8测试云客服"
        - name: BYTEDESK_CUSTOM_LOGO
          value: "http://59.211.236.64:30024/admin/icons/custom/zhiguitong.jpg"
        - name: BYTEDESK_CUSTOM_DESCRIPTION
          value: ""
        - name: BYTEDESK_CUSTOM_SHOW_RIGHT_CORNER_CHAT
          value: "false"
        - name: BYTEDESK_CUSTOM_SHOW_DEMO
          value: "false"
        - name: BYTEDESK_CUSTOM_PRIVACY_POLICY_URL
          value: ""
        - name: BYTEDESK_CUSTOM_TERMS_OF_SERVICE_URL
          value: ""
        - name: BYTEDESK_CUSTOM_LOGIN_USERNAME_ENABLE
          value: "true"
        - name: BYTEDESK_CUSTOM_LOGIN_MOBILE_ENABLE
          value: "true"
        - name: BYTEDESK_CUSTOM_LOGIN_EMAIL_ENABLE
          value: "false"
        - name: BYTEDESK_CUSTOM_LOGIN_SCAN_ENABLE
          value: "true"
        - name: BYTEDESK_CUSTOM_DOC_URL_SHOW
          value: "true"
        - name: BYTEDESK_CUSTOM_DOC_URL
          value: "https://www.weiyuai.cn/docs/zh-CN/"      
        # 管理员配置
        - name: BYTEDESK_ADMIN_EMAIL
          value: "admin@email.com"
        - name: BYTEDESK_ADMIN_PASSWORD
          value: "admin"
        - name: BYTEDESK_ADMIN_NICKNAME
          value: "SuperAdmin"
        - name: BYTEDESK_ADMIN_MOBILE
          value: "13345678000"
        - name: BYTEDESK_ADMIN_MOBILE_WHITELIST
          value: "18888888000,18888888001,18888888002,18888888003,18888888004,18888888005"
        - name: BYTEDESK_ADMIN_EMAIL_WHITELIST
          value: "100@email.com,101@email.com,102@email.com,103@email.com,104@email.com,105@email.com"
        - name: BYTEDESK_ADMIN_VALIDATE_CODE
          value: "123456"
        - name: BYTEDESK_ADMIN_FORCE_VALIDATE_MOBILE
          value: "true"
        - name: BYTEDESK_ADMIN_FORCE_VALIDATE_EMAIL
          value: "true"      
        # 成员配置
        - name: BYTEDESK_MEMBER_PASSWORD
          value: "admin@20250606"     
        # 组织配置
        - name: BYTEDESK_ORGANIZATION_NAME
          value: "MyCompany"
        - name: BYTEDESK_ORGANIZATION_CODE
          value: "bytedesk"
        # 功能配置
        - name: BYTEDESK_FEATURES_JAVA_AI
          value: "false"
        - name: BYTEDESK_FEATURES_PYTHON_AI
          value: "true"
        - name: BYTEDESK_FEATURES_EMAIL_TYPE
          value: "javamail"
        - name: BYTEDESK_FEATURES_ENABLE_REGISTRATION
          value: "false"
        - name: BYTEDESK_FEATURES_AVATAR_BASE_URL
          value: "http://59.211.236.64:30024" 
        # JWT配置
        - name: BYTEDESK_JWT_SECRET_KEY
          value: "1dfaf8d004207b628a9a6b859c429f49a9a7ead9fd8161c1e60847aeef06dbd2"
        - name: BYTEDESK_JWT_EXPIRATION
          value: "2592000000"
        - name: BYTEDESK_JWT_REFRESH_TOKEN_EXPIRATION
          value: "5184000000"
        # 数据库配置
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysql:3306/bytedesk_im?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true"
        - name: SPRING_DATASOURCE_USERNAME
          value: "root"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "mssql@admin2025"
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: "update"
        # Redis配置
        - name: SPRING_DATA_REDIS_HOST
          value: "redis"
        - name: SPRING_DATA_REDIS_PORT
          value: "6379"
        - name: SPRING_DATA_REDIS_PASSWORD
          value: "123456"
        - name: SPRING_DATA_REDIS_DATABASE
          value: "0"
        # 缓存配置
        - name: BYTEDESK_CACHE_LEVEL
          value: "0"
        - name: BYTEDESK_CACHE_PREFIX
          value: "bytedeskim"
        - name: BYTEDESK_CACHE_REDIS_STREAM_KEY
          value: "bytedeskim:stream"
        # 上传配置
        - name: BYTEDESK_UPLOAD_TYPE
          value: "local"
        - name: BYTEDESK_UPLOAD_DIR
          value: "/app/uploads"
        - name: BYTEDESK_UPLOAD_URL
          value: "http://59.211.236.64:30024"
        # 知识库配置
        - name: BYTEDESK_KBASE_THEME
          value: "default"
        - name: BYTEDESK_KBASE_HTML_PATH
          value: "helpcenter"
        - name: BYTEDESK_KBASE_API_URL
          value: "https://kf.gxzgt.com:9003"
        # Socket配置
        - name: BYTEDESK_SOCKET_HOST
          value: "0.0.0.0"
        - name: BYTEDESK_SOCKET_WEBSOCKET_PORT
          value: "9885"
        - name: BYTEDESK_SOCKET_LEAK_DETECTOR_LEVEL
          value: "SIMPLE"
        - name: BYTEDESK_SOCKET_PARENT_EVENT_LOOP_GROUP_THREAD_COUNT
          value: "1"
        - name: BYTEDESK_SOCKET_CHILD_EVENT_LOOP_GROUP_THREAD_COUNT
          value: "8"
        - name: BYTEDESK_SOCKET_MAX_PAYLOAD_SIZE
          value: "10240"
        - name: BYTEDESK_CLUSTER_ENABLED
          value: "false"
        # Druid配置
        - name: SPRING_DATASOURCE_DRUID_STAT_VIEW_SERVLET_LOGIN_USERNAME
          value: "admin@email.com"
        - name: SPRING_DATASOURCE_DRUID_STAT_VIEW_SERVLET_LOGIN_PASSWORD
          value: "admin"
        # Actuator配置
        - name: MANAGEMENT_ENDPOINTS_ENABLED_BY_DEFAULT
          value: "false"
        - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
          value: ""
        - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_EXCLUDE
          value: "*"
        - name: MANAGEMENT_ENDPOINT_HEALTH_ENABLED
          value: "false"
        - name: MANAGEMENT_ENDPOINT_INFO_ENABLED
          value: "false"
        - name: MANAGEMENT_SERVER_PORT
          value: "-1"
        - name: MANAGEMENT_ENDPOINTS_WEB_BASE_PATH
          value: "/management"
        - name: SPRING_SECURITY_BASIC_ENABLED
          value: "true"
        # AI配置 - Ollama
        - name: SPRING_AI_MODEL_CHAT
          value: "zhupuai"
        - name: SPRING_AI_MODEL_EMBEDDING
          value: "zhupuai"
        - name: SPRING_AI_OLLAMA_BASE_URL
          value: "http://10.11.8.123:11434"
        - name: SPRING_AI_OLLAMA_CHAT_ENABLED
          value: "false"
        - name: SPRING_AI_OLLAMA_CHAT_OPTIONS_MODEL
          value: "qwen3:0.6b"
        - name: SPRING_AI_OLLAMA_CHAT_OPTIONS_TEMPERATURE
          value: "0.7"
        - name: SPRING_AI_OLLAMA_EMBEDDING_ENABLED
          value: "false"
        - name: SPRING_AI_OLLAMA_EMBEDDING_OPTIONS_MODEL
          value: "bge-m3:latest"
        - name: SPRING_AI_OLLAMA_INIT_PULL_MODEL_STRATEGY
          value: "when_missing"
        - name: SPRING_AI_OLLAMA_EMBEDDING_OPTIONS_MODEL_RERANK
          value: "bge-reranker-v2-m3:latest"
        # AI配置 - 智谱AI
        - name: SPRING_AI_ZHIPUAI_API_KEY
          value: "2e9995f1e58a47e6ad4a4d8449582a53.DlPmMSZTU6adnha1"
        - name: SPRING_AI_ZHIPUAI_CHAT_ENABLED
          value: "true"
        - name: SPRING_AI_ZHIPUAI_CHAT_OPTIONS_MODEL
          value: "glm-4-flash"
        - name: SPRING_AI_ZHIPUAI_CHAT_OPTIONS_TEMPERATURE
          value: "0.7"
        - name: SPRING_AI_ZHIPUAI_EMBEDDING_ENABLED
          value: "true"
        # AI配置 - Deepseek
        - name: SPRING_AI_DEEPSEEK_BASE_URL
          value: "https://api.deepseek.com"
        - name: SPRING_AI_DEEPSEEK_API_KEY
          value: "sk-xxx"
        - name: SPRING_AI_DEEPSEEK_CHAT_ENABLED
          value: "false"
        - name: SPRING_AI_DEEPSEEK_CHAT_OPTIONS_MODEL
          value: "deepseek-chat"
        - name: SPRING_AI_DEEPSEEK_CHAT_OPTIONS_TEMPERATURE
          value: "0.7"
        - name: SPRING_AI_DEEPSEEK_EMBEDDING_ENABLED
          value: "false"
        # AI配置 - OpenAI
        - name: SPRING_AI_OPENAI_BASE_URL
          value: "https://api.openai.com"
        - name: SPRING_AI_OPENAI_API_KEY
          value: "sk-xxx"
        - name: SPRING_AI_OPENAI_CHAT_ENABLED
          value: "false"
        - name: SPRING_AI_OPENAI_CHAT_OPTIONS_MODEL
          value: "gpt-4o"
        - name: SPRING_AI_OPENAI_CHAT_OPTIONS_TEMPERATURE
          value: "0.7"
        - name: SPRING_AI_OPENAI_EMBEDDING_ENABLED
          value: "false"
        # AI配置 - 阿里云
        - name: SPRING_AI_DASHSCOPE_BASE_URL
          value: "https://dashscope.aliyuncs.com/compatible-mode"
        - name: SPRING_AI_DASHSCOPE_API_KEY
          value: "sk-xxx"
        - name: SPRING_AI_DASHSCOPE_CHAT_ENABLED
          value: "false"
        - name: SPRING_AI_DASHSCOPE_CHAT_OPTIONS_MODEL
          value: "deepseek-r1"
        - name: SPRING_AI_DASHSCOPE_CHAT_OPTIONS_TEMPERATURE
          value: "0.7"
        - name: SPRING_AI_DASHSCOPE_AUDIO_TRANSCRIPTION_ENABLED
          value: "false"
        - name: SPRING_AI_DASHSCOPE_IMAGE_ENABLED
          value: "false"
        - name: SPRING_AI_DASHSCOPE_EMBEDDING_ENABLED
          value: "false"
        - name: SPRING_AI_DASHSCOPE_AUDIO_SYNTHESIS_ENABLED
          value: "false"
        - name: SPRING_AI_NACOS_PROMPT_TEMPLATE_ENABLED
          value: "false"
        # 其他AI服务配置...
        # (此处应包含所有其他AI服务配置，格式同上)
        # Elasticsearch配置
        - name: SPRING_ELASTICSEARCH_URIS
          value: "http://elasticsearch8:9200"
        - name: SPRING_ELASTICSEARCH_USERNAME
          value: "elastic"
        - name: SPRING_ELASTICSEARCH_PASSWORD
          value: "ykfsft20250805"
        - name: SPRING_AI_VECTORSTORE_ELASTICSEARCH_ENABLED
          value: "true"
        - name: SPRING_AI_VECTORSTORE_ELASTICSEARCH_INITIALIZE_SCHEMA
          value: "true"
        - name: SPRING_AI_VECTORSTORE_ELASTICSEARCH_INDEX_NAME
          value: "bytedesk_vs_index"
        - name: SPRING_AI_VECTORSTORE_ELASTICSEARCH_DIMENSIONS
          value: "1024"
        - name: SPRING_AI_VECTORSTORE_ELASTICSEARCH_SIMILARITY
          value: "cosine"
        # Artemis JMS配置
        - name: SPRING_ARTEMIS_MODE
          value: "native"
        - name: SPRING_ARTEMIS_BROKER_URL
          value: "tcp://activemq:61616"
        - name: SPRING_ARTEMIS_USER
          value: "admin"
        - name: SPRING_ARTEMIS_PASSWORD
          value: "admin"
        - name: SPRING_JMS_LISTENER_CONCURRENCY
          value: "1"
        - name: SPRING_JMS_LISTENER_MAX_CONCURRENCY
          value: "10"
        - name: SPRING_JMS_LISTENER_ACKNOWLEDGE_MODE
          value: "client"
        - name: SPRING_JMS_LISTENER_AUTO_STARTUP
          value: "true"
        - name: SPRING_JMS_LISTENER_MAX_ATTEMPTS
          value: "5"
        - name: SPRING_JMS_LISTENER_INITIAL_INTERVAL
          value: "1000"
        - name: SPRING_JMS_LISTENER_MAX_INTERVAL
          value: "10000"
        - name: SPRING_JMS_LISTENER_MULTIPLIER
          value: "2.0"
        - name: SPRING_JMS_LISTENER_RECEIVE_TIMEOUT
          value: "1000"
        - name: SPRING_ARTEMIS_EMBEDDED_QUEUES
          value: "DLQ"
        - name: SPRING_JMS_LISTENER_MISSING_QUEUES_FATAL
          value: "false"
        # 数据库连接池配置
        - name: SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT
          value: "60000"
        - name: SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE
          value: "10"
        # 微信支付配置
        - name: WECHAT_PAY_ENABLED
          value: "false"
        # 阿里云短信配置
        - name: ALIYUN_SMS_SIGNNAME
          value: ""
        - name: ALIYUN_SMS_TEMPLATECODE
          value: ""
        # 文档配置
        - name: SPRINGDOC_SHOW_ACTUATOR
          value: "false"
        - name: SPRINGDOC_SWAGGER_UI_ENABLED
          value: "true"
        - name: SPRINGDOC_SWAGGER_UI_PATH
          value: "/index.html"
        - name: SPRINGDOC_API_DOCS_ENABLED
          value: "true"
        - name: SPRINGDOC_API_DOCS_PATH
          value: "/v3/api-docs"
        - name: KNIFE4J_ENABLED
          value: "true"
        - name: KNIFE4J_SETTING_LANGUAGE
          value: "zh_cn"
        resources:
          requests:
            cpu: 1
            memory: 2Gi
          limits:
            cpu: 1
            memory: 4Gi
        ports:
        - containerPort: 9003  # Core protocol
        - containerPort: 9885   # socket
