# 智谱AI配置示例
# 将此配置添加到 application.yml 中

zhipuai:
  enabled: true
  api-key: "your_zhipuai_api_key_here"  # 替换为你的智谱AI API密钥
  model: "glm-4"  # 默认模型
  temperature: 0.7  # 温度参数
  top-p: 0.9  # top-p参数
  max-tokens: 4096  # 最大token数
  connection-timeout: 30  # 连接超时时间（秒）
  read-timeout: 10  # 读取超时时间（秒）
  write-timeout: 10  # 写入超时时间（秒）
  ping-interval: 10  # ping间隔（秒）
  max-idle-connections: 8  # 最大空闲连接数
  keep-alive-duration: 1  # 连接保持时间（秒）

# 日志配置
logging:
  level:
    com.bytedesk.ai.zhipuai: DEBUG
    com.zhipu.oapi: DEBUG 