{{- if .Values.mysql.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bytedesk.fullname" . }}-mysql
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bytedesk.labels" . | nindent 4 }}
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: {{ include "mysql.image" . }}
        imagePullPolicy: {{ .Values.mysql.image.pullPolicy }}
        ports:
        - containerPort: 3306
          name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: {{ .Values.mysql.auth.rootPassword }}
        - name: MYSQL_DATABASE
          value: {{ .Values.mysql.auth.database }}
        - name: MYSQL_USER
          value: {{ .Values.mysql.auth.username }}
        - name: MYSQL_PASSWORD
          value: {{ .Values.mysql.auth.password }}
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
        resources:
          {{- toYaml .Values.mysql.resources | nindent 10 }}
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: {{ include "bytedesk.fullname" . }}-mysql-pvc
{{- end }} 